# Generated by Django 3.1.6 on 2022-02-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_bureau', '0002_stockmovement_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='output',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
