# Generated by Django 3.1.6 on 2022-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_bureau', '0003_auto_20220228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
